[project]
name = "elibrarian"
version = "0.1.0"
description = "A helper module to monitor ebook directories and organise"
authors = [
    {name = "Tom Freeman",email = "tomrfreeman3@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ebooklib (>=0.20,<0.21)",
    "pydantic (>=2.13.4,<3.0.0)",
    "ipykernel (>=7.3.0,<8.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "isbnlib (>=3.10.14,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
